apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${deployment.name}
  namespace: makersplatform
  labels:
    app: ${deployment.name}
    app.kubernetes.io/name: ${deployment.name}
    app.kubernetes.io/instance: ${deployment.name + deployment.instanceSuffix}
    app.kubernetes.io/version: ${deployment.version}
    app.kubernetes.io/component: ${deployment.component}
    app.kubernetes.io/part-of: ${deployment.partOf}
    app.kubernetes.io/managed-by: spinnaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${deployment.name}
  template:
    metadata:
      labels:
        app: ${deployment.name}
        app.kubernetes.io/name: ${deployment.name}
        app.kubernetes.io/instance: ${deployment.name}${instanceSuffix}
        app.kubernetes.io/version: ${deployment.version}
        app.kubernetes.io/component: ${deployment.component}
        app.kubernetes.io/part-of: ${deployment.partOf}
        app.kubernetes.io/managed-by: spinnaker
    spec:
      containers:
        - name: ${deployment.name}
          image: ${deployment.image}
